### ISSUE TITLE
pg_hba is not working 

### ISSUE THREAD

**Issue by angapov** [zalando-incubator/postgres-operator#330]
Whatever I put in cluster spec:
```
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
    - host    all all 0.0.0.0/0 md5
```
Inside container pg_hba.conf always looks the same rejecting non-local connections:
```
# cat /home/postgres/pgdata/pgroot/data/pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
local   all             all                                   trust
hostssl all             +zalandos    127.0.0.1/32       pam
host    all             all                127.0.0.1/32       md5
hostssl all             +zalandos    ::1/128            pam
host    all             all                ::1/128            md5
hostssl replication     standby all                md5
hostnossl all           all                all                reject
hostssl all             +zalandos    all                pam
hostssl all             all                all                md5
```

Am I missing something?
