### ISSUE TITLE
storageClassName on Statefulset

### ISSUE THREAD

**Issue by schmitch** [zalando-incubator/postgres-operator#337]
First of all, thanks for your great software!

Currently I have a problem with postgres-operator, because the `StatefulSet` that gets created does not work well with a local volume that has a `volumeBindingMode: WaitForFirstConsumer` and a `nodeAffinity` (i.e. local volumes).

Currently the problem is that, postgres-operator does not created a volumeClaimTemplate that contains `storageClassName: ""` instead it uses an annotation which does not work on new cluster versions.

i.e. I patched the method `generatePersistentVolumeClaimTemplate` to:
```
func generatePersistentVolumeClaimTemplate(volumeSize, volumeStorageClass string) (*v1.PersistentVolumeClaim, error) {
	metadata := metav1.ObjectMeta{
		Name: constants.DataVolumeName,
	}
	var storageClassName *string = nil
	if volumeStorageClass != "" {
		// TODO: check if storage class exists
		storageClassName = &volumeStorageClass
		metadata.Annotations = map[string]string{"volume.beta.kubernetes.io/storage-class": volumeStorageClass}
	} else {
		metadata.Annotations = map[string]string{"volume.alpha.kubernetes.io/storage-class": "default"}
	}

	quantity, err := resource.ParseQuantity(volumeSize)
	if err != nil {
		return nil, fmt.Errorf("could not parse volume size: %v", err)
	}

	volumeClaim := &v1.PersistentVolumeClaim{
		ObjectMeta: metadata,
		Spec: v1.PersistentVolumeClaimSpec{
			StorageClassName: storageClassName,
			AccessModes: []v1.PersistentVolumeAccessMode{v1.ReadWriteOnce},
			Resources: v1.ResourceRequirements{
				Requests: v1.ResourceList{
					v1.ResourceStorage: quantity,
				},
			},
		},
	}

	return volumeClaim, nil
}
```
after that it seems to work.

Is there a reason why the annotation is used instead of the StorageClassName?
Currently I think `StorageClassName` is supported **at least** since 1.8 so I guess there is no need to keep the annotation?

**Edit:  local-volume on minikube**
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "local-storage"
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /data/pv01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: In
          values:
          - minikube
```
