### ISSUE TITLE
CRD for OperatorConfiguration not registered

### ISSUE THREAD

**Issue by jens-totemic** [zalando-incubator/postgres-operator#404]
I'm facing difficulties using the CRD for `OperatorConfiguration`. Since it is the preferred configuration mechanism according to the manual, I'd like to replace the use of the config map approach with it. I'm following the steps at https://github.com/zalando-incubator/postgres-operator/blob/master/docs/reference/operator_parameters.md and added the environment variable `POSTGRES_OPERATOR_CONFIGURATION_OBJECT` in order to trigger installation of the CRD for `OperatorConfiguration`. Then I created the postgres operator using `kubectl apply`. 

When creating the postgres operator and calling `kubectl get crd` afterwards, I see this entry in the list of available CRDs: 
`postgresql-operator-configurations.acid.zalan.do` 
but instead I expected to see an entry:
`OperatorConfiguration`

According to commit https://github.com/zalando-incubator/postgres-operator/commit/e1ed4b847d527104fab7edc6b246cf6d67d77fd8 , the CRD `postgres-operator-configuration` should have been renamed to `OperatorConfiguration` but this does not seem to be happening currently.

This leads to the problem that I cannot use the example configuration from https://github.com/zalando-incubator/postgres-operator/blob/master/manifests/postgresql-operator-default-configuration.yaml. Trying to apply it fails since Kubernetes does not recognize the CRD `OperatorConfiguration`

Detailed steps to reproduce: 
```
kubectl apply -f https://raw.githubusercontent.com/zalando-incubator/postgres-operator/master/manifests/operator-service-account-rbac.yaml
```

Then download https://github.com/zalando-incubator/postgres-operator/blob/master/manifests/postgres-operator.yaml and modify it so it uses `POSTGRES_OPERATOR_CONFIGURATION_OBJECT`:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres-operator
    spec:
      serviceAccountName: zalando-postgres-operator
      containers:
      - name: postgres-operator
        image: registry.opensource.zalan.do/acid/postgres-operator:v1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_OPERATOR_CONFIGURATION_OBJECT
          value: postgresql-operator-default-configuration
```
And apply it using:
```
kubectl apply -f postgres-operator.yaml
```

Then list all CRDs using
```
kubectl get crd
```
And observe an entry named `postgresql-operator-configurations.acid.zalan.do`. There is no entry for `OperatorConfiguration`.

Then try to use the demo configuration
```
kubectl apply -f https://github.com/zalando-incubator/postgres-operator/blob/master/manifests/postgresql-operator-default-configuration.yaml
```
Observe the error message that Kubernetes does not recognize resource type `OperatorConfiguration`
